server:
  port: 8082

spring:
  application:
    name: magalu
  datasource:
    url: ${MYSQL_CONNECTION}   
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: default
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        ddl-create: create-drop
        format-sql: true
        generate-statistics: true
  main:
    banner-mode: "LOG"
    allow-bean-definition-overriding: true